class Article {
  final String text;
  final String domain;
  final String by;
  final String age;
  final int score;
  final int commentsCount;

  const Article({this.text, this.domain, this.by, this.age, this.score, this.commentsCount});
}

final articles = [
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'www.google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'www.google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'www.google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'www.google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'www.google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
  Article(
    text: 'lorem lorem lorem lorem lorem',
    age: '3 day',
    by: 'google.co.in',
    commentsCount: 12,
    domain: 'google.co.in',
    score: 150,
  ),
];
